env:
  commonjs: true
  es6: true
  node: true
extends: airbnb-base
parser: typescript-eslint-parser
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
